apiVersion: v1
kind: ConfigMap
metadata:
  name: crophealth-config
  namespace: crophealth
  labels:
    app.kubernetes.io/name: crophealth
    app.kubernetes.io/component: config
data:
  ENVIRONMENT: "production"
  PROJECT_NAME: "CropHealthAI"
  API_V1_STR: "/api/v1"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
  MAX_IMAGE_SIZE_MB: "10"
  STORAGE_BASE_URL: "/storage"
  ML_RUN_LOCAL: "true"
  AWS_REGION: "us-east-1"
