apiVersion: v1
kind: Service
metadata:
  name: crophealth-frontend
  namespace: crophealth
  labels:
    app.kubernetes.io/name: crophealth
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crophealth
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
