apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crophealth

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.template.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: crophealth-platform
